<?php

declare(strict_types=1);

use App\Controllers\Admin\AuditController;
use App\Controllers\Admin\AuthController;
use App\Controllers\Admin\AutomationController;
use App\Controllers\Admin\ComplianceController;
use App\Controllers\Admin\DashboardController;
use App\Controllers\Admin\ImportController;
use App\Controllers\Admin\ListingController as AdminListingController;
use App\Controllers\Admin\ReportAdminController;
use App\Controllers\Admin\SettingsController;
use App\Controllers\Admin\SetupController;
use App\Controllers\Admin\TaxonomyController;
use App\Controllers\AgeController;
use App\Controllers\ApiController;
use App\Controllers\DirectoryController;
use App\Controllers\HealthController;
use App\Controllers\HomeController;
use App\Controllers\LegalController;
use App\Controllers\ReportController;
use App\Controllers\SearchController;
use App\Controllers\SitemapController;
use App\Core\Router;

return static function (Router $router): void {
    $router->get('/', [HomeController::class, 'index']);
    $router->get('/health', [HealthController::class, 'index']);
    $router->get('/age', [AgeController::class, 'prompt']);
    $router->post('/age', [AgeController::class, 'confirm']);
    $router->get('/search', [SearchController::class, 'index']);
    $router->get('/terms', [LegalController::class, 'terms']);
    $router->get('/privacy', [LegalController::class, 'privacy']);
    $router->get('/content-policy', [LegalController::class, 'contentPolicy']);
    $router->get('/contact', [LegalController::class, 'contact']);
    $router->post('/contact', [LegalController::class, 'contact']);
    $router->get('/report', [ReportController::class, 'form']);
    $router->post('/report', [ReportController::class, 'store']);
    $router->get('/remove-listing', [ReportController::class, 'removal']);
    $router->post('/remove-listing', [ReportController::class, 'store']);
    $router->get('/api/states', [ApiController::class, 'states']);
    $router->get('/api/categories', [ApiController::class, 'categories']);
    $router->get('/api/cities', [ApiController::class, 'cities']);
    $router->get('/api/locations', [ApiController::class, 'localities']);
    $router->get('/sitemap.xml', [SitemapController::class, 'index']);
    $router->get('/sitemap-pages.xml', [SitemapController::class, 'pages']);
    $router->get('/sitemap-categories.xml', [SitemapController::class, 'categories']);
    $router->get('/sitemap-locations.xml', [SitemapController::class, 'locations']);
    $router->get('/sitemap-listings.xml', [SitemapController::class, 'listings']);
    $router->get('/robots.txt', [SitemapController::class, 'robots']);

    $router->get('/admin/login', [AuthController::class, 'login']);
    $router->post('/admin/login', [AuthController::class, 'login']);
    $router->post('/admin/logout', [AuthController::class, 'logout']);
    $router->get('/admin', [DashboardController::class, 'index']);
    $router->get('/admin/listings', [AdminListingController::class, 'index']);
    $router->get('/admin/listings/create', [AdminListingController::class, 'create']);
    $router->post('/admin/listings', [AdminListingController::class, 'save']);
    $router->get('/admin/listings/{id}/edit', [AdminListingController::class, 'edit']);
    $router->post('/admin/listings/{id}', [AdminListingController::class, 'save']);
    $router->post('/admin/listings/{id}/action', [AdminListingController::class, 'action']);
    $router->get('/admin/categories', [TaxonomyController::class, 'categories']);
    $router->post('/admin/categories', [TaxonomyController::class, 'categories']);
    $router->get('/admin/states', [TaxonomyController::class, 'states']);
    $router->post('/admin/states', [TaxonomyController::class, 'states']);
    $router->get('/admin/cities', [TaxonomyController::class, 'cities']);
    $router->post('/admin/cities', [TaxonomyController::class, 'cities']);
    $router->get('/admin/locations', [TaxonomyController::class, 'locations']);
    $router->post('/admin/locations', [TaxonomyController::class, 'locations']);
    $router->get('/admin/import', [ImportController::class, 'index']);
    $router->post('/admin/import', [ImportController::class, 'index']);
    $router->get('/admin/reports', [ReportAdminController::class, 'index']);
    $router->post('/admin/reports/{id}', [ReportAdminController::class, 'update']);
    $router->get('/admin/automation', [AutomationController::class, 'index']);
    $router->post('/admin/automation', [AutomationController::class, 'save']);
    $router->post('/admin/automation/run', [AutomationController::class, 'run']);
    $router->get('/admin/seo', [SettingsController::class, 'seo']);
    $router->get('/admin/settings', [SettingsController::class, 'settings']);
    $router->get('/admin/system/setup', [SetupController::class, 'index']);
    $router->post('/admin/system/setup', [SetupController::class, 'index']);
    $router->get('/admin/admins', [SettingsController::class, 'admins']);
    $router->post('/admin/admins', [SettingsController::class, 'admins']);
    $router->get('/admin/audit', [AuditController::class, 'index']);
    $router->get('/admin/compliance', [ComplianceController::class, 'index']);

    $router->fallback([DirectoryController::class, 'resolve']);
};
